insert into public.species (
  common_name,
  scientific_name,
  family,
  origin,
  water_needs,
  light_needs,
  soil,
  humidity,
  temperature,
  about,
  care_summary,
  care_difficulty,
  watering,
  sunlight,
  temperature_range,
  temperature_notes,
  soil_type,
  soil_ph_min,
  soil_ph_max,
  soil_mix,
  care_tips,
  profile_generated_at,
  profile_source
)
values
  (
    'Snake Plant',
    'Dracaena trifasciata',
    'Asparagaceae',
    'West Africa',
    'Low',
    'Low–Bright, indirect',
    'Well-draining',
    'Low–Moderate',
    '60–80°F',
    'Tough, great for beginners.',
    'Snake plants are resilient succulents that thrive on neglect and purify indoor air.',
    'Easy',
    'Allow soil to dry completely between waterings; less is more during winter.',
    'Handles low light but loves bright, filtered light for faster growth.',
    '60-85°F',
    'Keep above 50°F; cooler nights are tolerated but avoid drafts.',
    'Cactus or succulent mix with extra perlite or pumice.',
    5.5,
    7.5,
    array['cactus mix', 'perlite', 'pumice'],
    array['Rotate the pot every few weeks to keep growth upright.', 'Wipe leaves to remove dust and help photosynthesis.'],
    now(),
    'seed'
  ),
  (
    'Monstera',
    'Monstera deliciosa',
    'Araceae',
    'Central America',
    'Moderate',
    'Bright, indirect',
    'Chunky, well-draining',
    'Moderate–High',
    '65–85°F',
    'Iconic split leaves, fast grower.',
    'Monstera thrives with consistent moisture, high humidity, and room to climb.',
    'Moderate',
    'Water when the top 2 inches of soil are dry; ensure excess drains away.',
    'Prefers bright, indirect light; tolerate brief dappled sun indoors.',
    '65-85°F',
    'Protect from cold drafts; growth slows below 60°F.',
    'Aroid mix with bark, perlite, and coco coir.',
    5.5,
    7.0,
    array['coco coir', 'orchid bark', 'perlite'],
    array['Support with a moss pole to encourage fenestrated leaves.', 'Mist or use a humidifier during dry months.'],
    now(),
    'seed'
  );
